FROM nginx
MAINTAINER @jakeschmitz
RUN apt-get update -qq && apt-get -y install apache2-utils
ENV RAILS_ROOT /usr/src/app
WORKDIR $RAILS_ROOT
COPY config/nginx.conf /etc/nginx/conf.d/default.conf
#COPY config/localhost.crt /etc/ssl/certs/localhost.crt
#COPY config/localhost.key /etc/ssl/private/localhost.key

EXPOSE 80
EXPOSE 443
CMD [ "nginx", "-g", "daemon off;" ]
